sudo: required
language: python
python:
  - "3.5"
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - make html
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$SESAMCI_DOCKER_PASSWORD" | docker login -u "$SESAMCI_DOCKER_USERNAME" --password-stdin; make docker; fi
